package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	ClusterID        *string                `json:",omitempty"`
	KubeConfig       *string                `json:",omitempty"`
	Repository       *string                `json:",omitempty"`
	Chart            *string                `json:",omitempty"`
	Namespace        *string                `json:",omitempty"`
	Name             *string                `json:",omitempty"`
	Values           []string               `json:",omitempty"`
	Version          *string                `json:",omitempty"`
	ValueOverrideURL *string                `json:",omitempty"`
	ID               *string                `json:",omitempty"`
	Resources        map[string]interface{} `json:",omitempty"`
	TimeOut          *int                   `json:",omitempty"`
}
